-- Add Insulation Contractors Of Arizona
INSERT INTO contractors (
  business_name,
  name,
  email,
  phone,
  website,
  category,
  specialties,
  description,
  street_address,
  city,
  state,
  zip_code,
  latitude,
  longitude,
  status,
  verified,
  rating,
  review_count,
  years_in_business
) VALUES (
  'Insulation Contractors Of Arizona',
  'Insulation Contractors Of Arizona',
  'info@insulationcontractorsofarizona.com',
  '+1 623-241-1939',
  'https://insulationcontractorsofarizona.com/',
  'Insulation',
  '["Insulation Installation", "Energy Efficiency", "Attic Insulation", "Wall Insulation"]',
  'Professional insulation contractors serving the Greater Phoenix area. Specializing in residential and commercial insulation services.',
  '10616 N 50th Ave',
  'Glendale',
  'AZ',
  '85304',
  33.6135,
  -112.1746,
  'active',
  true,
  4.8,
  0,
  10
);
