[build]
  base = "apps/web"
  command = "pnpm build"
  publish = "dist"

# Environment variables (set these in Netlify UI)
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/dev/null"
  # Disable secrets scanning for public Google Maps API key
  SECRETS_SCAN_OMIT_KEYS = "PUBLIC_GOOGLE_MAPS_API_KEY"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

# Disable automatic image optimization (we're using local static images)
[images]
  remote_images = []

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Dev server settings
[dev]
  command = "pnpm dev"
  port = 4321
  targetPort = 4321
  framework = "#custom"
  autoLaunch = false
